spring:
  datasource:
    # 'db' - the Database service from docker-compose.yml
    url: jdbc:postgresql://db:5432/tourplanner_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # creates tables automatically  
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Location for external image storage
storage:
  location: /app/images 

# Logging configuration
logging:
  file:
    name: logs/tour-planner.log 